services:
  # Services
  webserver:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./conf/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    profiles:
      - website
  mongo:
    image: mongo:4-bionic
    ports:
      - 27017:27017
    volumes:
      - db-data:/var/lib/mongodb
    profiles:
      - website
      - bot

  # Our shitcode
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PACKAGE_NAME: boat
    image: powercord-boat
    working_dir: /opt/porkord/packages/boat
    command: pnpm run dev -- --noClear
    volumes:
      - ./packages/boat/src:/opt/porkord/packages/boat/src
      - ./packages/boat/package.json:/opt/porkord/packages/boat/package.json
      - ./packages/boat/tsconfig.json:/opt/porkord/packages/boat/tsconfig.json
      - ./config.json:/opt/porkord/config.json
    profiles:
      - bot
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PACKAGE_NAME: api
    image: powercord-api
    working_dir: /opt/porkord/packages/api
    command: pnpm run dev -- --noClear
    volumes:
      - ./packages/api/src:/opt/porkord/packages/api/src
      - ./packages/api/package.json:/opt/porkord/packages/api/package.json
      - ./packages/api/tsconfig.json:/opt/porkord/packages/api/tsconfig.json
      - ./documentation:/opt/porkord/documentation
      - ./config.json:/opt/porkord/config.json
    profiles:
      - website
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PACKAGE_NAME: web
    image: powercord-web
    command: pnpm run dev
    working_dir: /opt/porkord/packages/web
    volumes:
      - ./packages/web:/opt/porkord/packages/web
    profiles:
      - website

volumes:
  db-data:
    driver: local
