services:
  # Services
  webserver:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    profiles:
      - website
  mongo:
    image: mongo:4-bionic
    ports:
      - 9042:9042
    volumes:
      - db-data:/var/lib/mongodb
    profiles:
      - website
      - bot

  # Our shitcode
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PACKAGE_NAME: boat
    image: powercord-boat
    working_dir: /opt/porkord/packages/boat
    command: pnpm run dev -- --noClear
    volumes:
      - ./packages/boat:/opt/porkord/packages/boat
      - ./config.json:/opt/porkord/config.json
    profiles:
      - bot
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PACKAGE_NAME: api
    image: powercord-api
    working_dir: /opt/porkord/packages/api
    command: pnpm run dev -- --noClear
    volumes:
      - ./packages/api:/opt/porkord/packages/api
      - ./documentation:/opt/porkord/documentation
      - ./config.json:/opt/porkord/config.json
    profiles:
      - website
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PACKAGE_NAME: web
    image: powercord-web
    command: pnpm run dev
    working_dir: /opt/porkord/packages/web
    volumes:
      - ./packages/web:/opt/porkord/packages/web
    profiles:
      - website

volumes:
  db-data:
    driver: local
